### ISSUE TITLE
model.py and model2.py differences

### ISSUE THREAD

**Issue by murdav** [thimabru1010/ResUnet-a_mltsk_keras#3]
Dear @thimabru1010,

I noticed there are two files `model.py` and `model2.py`.

In my experiments, I am using `model.py` but I am wondering what it could be the difference related to the following line https://github.com/thimabru1010/ResUnet-a_mltsk_keras/blob/master/ResUnet_a/model2.py#L26

Thank you in advance.

Davide

**Comment by thimabru1010** [comment]
Hello @murdav,

You should use `model2.py`. In `model.py` I was missing the residual part on ResBlock, I was just applying convolutions. Then, the comment a forgot to delete after correcting the residual part.

**Comment by murdav** [comment]
Thank you for your clarification.

Davide
